apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collector
  name: collector-deploy
spec:
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/weplanx/collector:latest
          imagePullPolicy: Always
          name: collector
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: collector.cfg
            items:
              - key: "config.yml"
                path: "config.yml"